package com.jfinal.controller;

import com.jfinal.core.Controller;
import com.jfinal.service.UserService;
import com.jfinal.utils.BeanContext;

/**
 * Generated by lee.
 */
public class UserController extends Controller {
	private UserService service = BeanContext.getBean(UserService.class);

	protected UserService getService() {
		return service;
	}
	
}
